### ISSUE TITLE
CS8120: switch case unreachable when using default="true" command since v0.8.0

### ISSUE THREAD

**Issue by chklauser** [xb-bx/CommandLineArgsGenerator#1]
# Scenario
Using a default command (`default="true"` in a `<summary>` tag) with CommandLineArgsGenerator  version 0.8.0

# Observed Behaviour
 CommandLineArgsGenerator v0.8.0 generates a switch statement with two conflicting cases in `EntryPoint.cs`:

```csharp
case string _TheDefaultCommand:
    // argument parsing for the default command

case string something_unknown:
    // suggestions  + "unknown command" error
```

# Workaround
Downgrade to `0.7.9`, which generates a `default:` case instead. The default case will probably never be hit, as none of the arguments will ever be `null`. `null` is the only value _not_ matched by the `string _TheDefaultCommand` pattern.

# Thanks
Thanks for making CommandLineArgsGenerator ❤️ I think having the code for command line parsing generated (instead of using Reflection) is super valuable for keeping CLI startup times short. For my hobby use case, I'm perfectly content using 0.7.9.

**Comment by xb-bx** [comment]
Oh, thx for your feedback. I'll fix it ASAP

**Comment by xb-bx** [comment]
Could you create minimal repro project?

**Comment by chklauser** [comment]
I've created the reproduction as a PR that adds an example: https://github.com/xb-bx/CommandLineArgsGenerator/pull/2

Please do feel free to close the PR if you'd prefer not to have such an example in the code base :)

**Comment by xb-bx** [comment]
Thx again
